baseURL = "https://botanyse.github.io/personal-blog/"
theme = "hugo-bearblog"
title = "Belacqwa"
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
canonifyURLs = true

[permalinks]
  blog = "/:slug/"

[params]
  description = "My personal blog"
  hideMadeWithLine = true
  math = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Readings"
    url = "/readings/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
  

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\\(', '\\)'], ['$', '$']]

